name: UI & API Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ae-tests .

      # ---------------- API tests ----------------
      - name: Run API tests
        id: api_tests
        continue-on-error: true
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            ae-tests uv run pytest -m api

      # ---------------- UI tests ----------------
      - name: Run UI tests
        id: smoke_and_ui_tests
        continue-on-error: true
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/reports:/app/reports \
            -v ${{ github.workspace }}/test-results:/app/test-results \
            ae-tests uv run pytest -m "smoke or ui" \
              --tracing retain-on-failure \
              --screenshot only-on-failure

      # ---------------- Reports ----------------
      - name: Upload reports (API + UI)
        if: steps.api_tests.outcome == 'failure' || steps.smoke_and_ui_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/

      - name: Upload UI artifacts (traces, screenshots)
        if: steps.smoke_and_ui_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: ui-artifacts
          path: test-results/

      # ------- Fail the job explicitly ---------
      - name: Fail pipeline if tests failed
        if: steps.api_tests.outcome == 'failure' || steps.smoke_and_ui_tests.outcome == 'failure'
        run: exit 1
